### ISSUE TITLE
项目报错，运行不起来，建议币编主及时更新

### ISSUE THREAD

**Issue by Andrew5** [kaina404/DouBanProject#100]
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to
the V2 embedding.
Take a look at the docs for migrating an app:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by 904783413** [comment]
我也一样

**Comment by huangchengzuo** [comment]
你好！
邮件已收到！谢谢！

**Comment by 904783413** [comment]
现在好了吗

**Comment by kaina404** [comment]
项目已经更新到最新版本拉，可以pull并且直接运行了。
