### ISSUE TITLE
一运行就崩溃

### ISSUE THREAD

**Issue by leo-andr** [kaina404/DouBanProject#107]
Android设备
一安装进去就崩溃
信息只有这些
I/flutter (32685): ====数据库所在文件夹: /data/user/0/com.toly1994.flutter_unit/databases=======
E/Dart    (32685): ../../third_party/dart/runtime/vm/message_snapshot.cc: 2185: error: unreachable code
E/DartVM  (32685): version=2.19.0-312.0.dev (dev) (Thu Oct 13 23:30:14 2022 -0700) on "android_arm64"
E/DartVM  (32685): pid=32685, thread=499, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
E/DartVM  (32685): os=android, arch=arm64, comp=yes, sim=no
E/DartVM  (32685): isolate_instructions=0, vm_instructions=7e138d2880
E/DartVM  (32685):   pc 0x0000007e139f0cac fp 0x0000007cfcef6420 /data/app/com.toly1994.flutter_unit-cykrIIU0cp02hGI-HjP4eA==/lib/arm64/libflutter.so+0x1b67cac
E/DartVM  (32685): -- End of DumpStackTrace
F/libc    (32685): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 499 (DartWorker), pid 32685 (94.flutter_unit)
Softversion: PD2034C_A_1.13.6
Time: 2022-11-23 12:17:38
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'vivo/PD2034/PD2034:10/QP1A.190711.020/compiler08151454:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-11-23 12:17:38+0800
pid: 32685, tid: 499, name: DartWorker  >>> com.toly1994.flutter_unit <<<
uid: 10265
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '../../third_party/dart/runtime/vm/message_snapshot.cc: 2185: error: unreachable code'
    x0  0000000000000000  x1  00000000000001f3  x2  0000000000000006  x3  0000007cfcef63a0
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000080
    x8  00000000000000f0  x9  8bb52923f978f0ab  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000000000038  x14 0000000000000001  x15 0000000000000010
    x16 0000007f02073738  x17 0000007f02051f40  x18 0000007cfc674000  x19 0000000000007fad
    x20 00000000000001f3  x21 00000000ffffffff  x22 0000000000000005  x23 0000000000000003
    x24 7ffffffffffffff8  x25 1000000000000000  x26 0000000000000005  x27 00000000004c4b40
    x28 0000000000000000  x29 0000007cfcef6440
    sp  0000007cfcef6380  lr  0000007f0200386c  pc  0000007f02003898
backtrace:
      #00 pc 0000000000073898  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 06bff8f604b0d37dc8b11a90d9c3cea0)
      #01 pc 0000000001a48ad4  /data/app/com.toly1994.flutter_unit-cykrIIU0cp02hGI-HjP4eA==/lib/arm64/libflutter.so (BuildId: 028b864a89f3a2ef0aa74d930c3e1b115e1c1f48)
      #02 pc 0000000001ad3a50  /data/app/com.toly1994.flutter_unit-cykrIIU0cp02hGI-HjP4eA==/lib/arm64/libflutter.so (BuildId: 028b864a89f3a2ef0aa74d930c3e1b115e1c1f48)
      #03 pc 00000000000fd804  [anon:libc_malloc]
Lost connection to device.

**Comment by huangchengzuo** [comment]
你好！
邮件已收到！谢谢！

**Comment by leo-andr** [comment]
提错了项目
