### ISSUE TITLE
个人体验总结

### ISSUE THREAD

**Issue by ikimiler** [kaina404/DouBanProject#12]
一个字：卡

**Comment by kaina404** [comment]
你可是使用release版本尝试一下👌

**Comment by kaina404** [comment]
@andmizi Release版本 https://pan.baidu.com/s/12OOywTiegrfwLIitodxrwg

**Comment by ikimiler** [comment]
谢谢了，release确实好很多 😄

**Comment by fubd** [comment]
环境：HUAWEI honor8，Android8.0
release版本卡顿感觉还是明显啊，特别是"书影音模块"，顶部的tab切换

**Comment by fubd** [comment]
不过 页面还原度挺不错
