### ISSUE TITLE
项目运行不起来报"/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory"

### ISSUE THREAD

**Issue by guoguozaichangge** [kaina404/DouBanProject#18]
<img width="1145" alt="屏幕快照 2019-05-11 上午1 24 23" src="https://user-images.githubusercontent.com/16694820/57545101-e61fc180-738b-11e9-84e3-6593e844eb27.png">

**Comment by kaina404** [comment]
@guoguozaichangge 你可以尝试删除下pod，然后重新安装试一试
