### ISSUE TITLE
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.  Because doubanapp requires SDK version >=2.1.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by lichtung-shack** [kaina404/DouBanProject#19]
项目导入idea报错，是flutter版本问题吗
![image](https://user-images.githubusercontent.com/49744258/57592615-3b192e80-756a-11e9-847e-56937a84e1f8.png)

**Comment by kaina404** [comment]
@KeelHsu 是的版本不一致，你的flutter版本是2.1.0dev，但是项目中的是2.1.0 你可以升级下你的版本

**Comment by lichtung-shack** [comment]
@kaina404 更新之后解决了，谢谢
