### ISSUE TITLE
项目启动不起来

### ISSUE THREAD

**Issue by taozhixiang** [kaina404/DouBanProject#22]
Compiler message:
lib/widgets/image/cached_network_image.dart:463:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/FlutterSDK/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on C:\WorkSpace\Android\FlutterDouBan-master-new\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by kaina404** [comment]
@taozhixiang 这个问题 我还真没遇到过。。。

**Comment by taozhixiang** [comment]
我已经解决了。应该是我flutter sdk的版本比较高的缘故。我把版本降下来后就可以了。

**Comment by taozhixiang** [comment]
@kaina404 我已经解决了。应该是我flutter sdk的版本比较高的缘故。我把版本降下来后就可以了。
