### ISSUE TITLE
项目跑不起来 ImageStreamListener

### ISSUE THREAD

**Issue by Yzc-jason** [kaina404/DouBanProject#32]
{
	"owner": "dart",
	"code": "argument_type_not_assignable",
	"severity": 8,
	"message": "The argument type '(ImageInfo, bool) → void' can't be assigned to the parameter type 'ImageStreamListener'.",
	"source": "dart",
	"startLineNumber": 197,
	"startColumn": 38,
	"endLineNumber": 197,
	"endColumn": 57,
	"tags": []
}

**Comment by kaina404** [comment]
有完整日志么？你的flutter  sdk跟Markdown上的一致么？

**Comment by leifu1107** [comment]
同上

**Comment by kaina404** [comment]
fwfwfw @

**Comment by kaina404** [comment]
[在这里讨论](https://github.com/kaina404/FlutterDouBan/issues/33)
