### ISSUE TITLE
跑不了 

### ISSUE THREAD

**Issue by zufeng1987** [kaina404/DouBanProject#33]
可能是我不会操作 
运行 flutter run 提示如下
Compiler message:
lib/widgets/image/cached_network_image.dart:197:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
lib/widgets/image/cached_network_image.dart:198:32: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      _imageStream.addListener(_handleImageChanged);
                               ^
lib/widgets/image/cached_network_image.dart:208:34: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
lib/widgets/image/cached_network_image.dart:463:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///E:/kaifa/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/palette_generator-0.1.1/lib/palette_generator.dart:188:29: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      stream.removeListener(imageListener);
                            ^
file:///E:/kaifa/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/palette_generator-0.1.1/lib/palette_generator.dart:194:31: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
        stream.removeListener(imageListener);
                              ^
file:///E:/kaifa/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/palette_generator-0.1.1/lib/palette_generator.dart:201:24: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/kaifa/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.addListener(imageListener);
                       ^
Compiler failed on E:\kaifa\yuanma\FlutterDouBan-master-new\lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'E:\kaifa\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 691

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugX86'.
> Process 'command 'E:\kaifa\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to
get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by kaina404** [comment]
你的flutter sdk是多少

**Comment by zufeng1987** [comment]
> 你的flutter sdk是多少

E:\kaifa\flutter\flutter\bin 这是flutter 的 
E:\kaifa\Android_Studio\SDK 这是 AS的

**Comment by kaina404** [comment]
版本号 @zufeng1987

**Comment by kaina404** [comment]
你执行flutter --version

**Comment by zufeng1987** [comment]
flutter 是 1.7.4

**Comment by zufeng1987** [comment]
PS E:\kaifa\yuanma\FlutterDouBan-master-new> flutter --version
Flutter 1.7.4 • channel dev • https://github.com/flutter/flutter.git
Framework • revision dfecafa4ab (5 days ago) • 2019-06-14 09:46:23 -0700
Engine • revision 2589785b5c
Tools • Dart 2.4.0

**Comment by kaina404** [comment]
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (7 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by kaina404** [comment]
这是我的：
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (7 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by zufeng1987** [comment]
哦哦 就是要下个 1.5.4 对吧

**Comment by kaina404** [comment]
你可以切换下flutter sdk版本 跑一下，还有pubspec.yaml的配置文件的版本号不要变化。

**Comment by zufeng1987** [comment]
这个 我百度下 我初学 什么都不懂 ....

**Comment by kaina404** [comment]
@zufeng1987 一步步来，都是这么过来的。

**Comment by zufeng1987** [comment]
嗯 谢谢啦 有什么微信群什么的吗 我想多点渠道学起来快点

**Comment by kaina404** [comment]
@zufeng1987 我在这个群里：468010872，目前有897人了

**Comment by zufeng1987** [comment]
好的 谢谢了

**Comment by kaina404** [comment]
@zufeng1987 如果你还有看这个项目，更新代码即可解决这个问题。谢谢

**Comment by x307799853** [comment]
我拉取了master-new最新代码，也是这个错误。
运行版本：
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by x307799853** [comment]
Compiler message:
lib/util/palette_generator.dart:187:5: Error: 'ImageStreamListener' isn't a type.
    ImageStreamListener l;
    ^^^^^^^^^^^^^^^^^^^
lib/util/palette_generator.dart:195:9: Error: Method not found: 'ImageStreamListener'.
    l = ImageStreamListener(imageListener);
        ^^^^^^^^^^^^^^^^^^^
Compiler failed on D:\flutter\flutterDouBan\lib/main.dart

**Comment by liangtongdev** [comment]
同样的问题
---------------------------------------------------------------------------------
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===

    Compiler message:
    lib/util/palette_generator.dart:187:5: Error: 'ImageStreamListener' isn't a type.
        ImageStreamListener l;
        ^^^^^^^^^^^^^^^^^^^
    lib/util/palette_generator.dart:195:9: Error: Method not found: 'ImageStreamListener'.
        l = ImageStreamListener(imageListener);
            ^^^^^^^^^^^^^^^^^^^
    Compiler failed on /Users/liangtong/Documents/fun/flutter/FlutterDouBan/lib/main.dart
    Failed to package /Users/liangtong/Documents/fun/flutter/FlutterDouBan.

Could not build the precompiled application for the device.

**Comment by yestodayHadRain** [comment]
我也遇到了这个问题了,然后把flutter版本升级到和作者一样的ImageStreamListener还是报错
```
Flutter 1.5.4 • channel unknown • unknown source
Framework • revision b593f5167b (1 year, 6 months ago) • 2019-04-22 07:51:33 -0700
Engine • revision ca31a7c57b
Tools • Dart 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)
```
