### ISSUE TITLE
flutter模板

### ISSUE THREAD

**Issue by baddate** [kaina404/DouBanProject#40]
请问[home_app_bar.dart](https://github.com/kaina404/FlutterDouBan/blob/master-new/lib/pages/home/home_app_bar.dart)是用了什么模板吗？

**Comment by kaina404** [comment]
你说的模板是？

**Comment by baddate** [comment]
> 你说的模板是？

是用的dart自带的库里面的文件吗？

**Comment by kaina404** [comment]
@baddate 如果你指的是首页的特效的话，那个是我基于原生库改动实现的。
