### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by ZHMzzz** [kaina404/DouBanProject#44]
小米Note手机，安卓7.0 
和原生豆瓣相比，性能明显差很多，Flutter非常卡。我在开发者模式打开gpu监控，发现滑动listview时gpu不调用，原生的会调用。
我自己做的小demo百姓生活+和微信小程序相比也有性能差距。。。
这种性能非常担忧啊，体验差距明显。

**Comment by kaina404** [comment]
release模式的 应该很流畅啊。你确定你的是release么

**Comment by ZHMzzz** [comment]
确定啊，源码跑过release和profile，也下载过你打的包，都非常卡，和原生豆瓣差距明显。骁龙810的处理器，滑动时不调用gpu

**Comment by kaina404** [comment]
@ZHMzzz 你是扫码下载的么？我用的mi9测试的，很流畅啊

**Comment by ZHMzzz** [comment]
mi9肯定不卡啊，我的意思是老旧设备上的性能差距

**Comment by ZHMzzz** [comment]
不是你写的问题，我写的demo也卡，F的优化还是有段路要走

**Comment by kaina404** [comment]
@ZHMzzz 了解了解了 谢谢
