### ISSUE TITLE
json字符串解析到model类过于复杂

### ISSUE THREAD

**Issue by SEUCalvin** [kaina404/DouBanProject#45]
可拓展性很差，每个字段都要手动解析，有点无法接受。期待更加方便的处理方式

**Comment by kaina404** [comment]
@SEUCalvin 这是使用三方工具自动解析的，而且dart语言的json解析目前好像就只能这样。

**Comment by SEUCalvin** [comment]
请问用的是什么第三方工具呀

**Comment by kaina404** [comment]
@SEUCalvin json2dart还是什么，具体忘了。

**Comment by SEUCalvin** [comment]
找到了，谢谢。http://www.devio.org/io/tools/json-to-dart/
