### ISSUE TITLE
请问热更新怎么搞啊

### ISSUE THREAD

**Issue by fansiyao** [kaina404/DouBanProject#47]

**Comment by kaina404** [comment]
你说微信的么？

**Comment by fansiyao** [comment]
flutter 不支持，尴尬




------------------ 原始邮件 ------------------
发件人: "Haoqun Jiang"<notifications@github.com>; 
发送时间: 2019年9月17日(星期二) 晚上7:13
收件人: "kaina404/FlutterDouBan"<FlutterDouBan@noreply.github.com>; 
抄送: "原点"<645127912@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kaina404/FlutterDouBan] 请问热更新怎么搞啊 (#47)




你说微信的么？

**Comment by kaina404** [comment]
是的
