### ISSUE TITLE
iOS Build Failed

### ISSUE THREAD

**Issue by smallMotorFly** [kaina404/DouBanProject#66]
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    Failed to build bundle.
    Failed to package /Users/xxxxx/flutterProject/FlutterDouBan-master-new.

**Comment by smallMotorFly** [comment]
https://github.com/kaina404/FlutterDouBan/issues/63#issuecomment-566971402 这个帮我解决了，感谢。

**Comment by aiyouBug** [comment]
这两个环境建议升级下
flutter_cache_manager: ^1.1.3
cached_network_image: ^2.0.0
