### ISSUE TITLE
The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.

### ISSUE THREAD

**Issue by VelvetDream** [kaina404/DouBanProject#68]
你好，我是一个新手，从第一个版本开始学习，最近好几个版本都发现有版本报错

 **Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.**
**报错代码片段1：**` 
...
```
 void resolve(CachedNetworkImageProvider provider) {
    final ImageStream oldImageStream = _imageStream;
    _imageStream = provider.resolve(createLocalImageConfiguration(state.context,
        size: widget.width != null && widget.height != null
            ? new Size(widget.width, widget.height)
            : null));

    if (_imageStream.key != oldImageStream?.key) {
      oldImageStream?.removeListener(_handleImageChanged);
      _imageStream.addListener(_handleImageChanged);
    }
  }

  void _handleImageChanged(ImageInfo imageInfo, bool synchronousCall) {
    _imageInfo = imageInfo;
    listener();
  }

  void stopListening(ImageInfo imageInfo, bool synchronousCall) {
    _imageStream?.removeListener(_handleImageChanged);
  }
}
...
```
`
**报错代码片段2：**
`
```
...
@override
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
    return new MultiFrameImageStreamCompleter(
        codec: _loadAsync(key),
        scale: key.scale,
        informationCollector: (StringBuffer information) {
          information.writeln('Image provider: $this');
          information.write('Image key: $key');
        });
  }
...
```
`

**报错版本：**(https://github.com/kaina404/FlutterDouBan/tree/efa9838be2099bc326117ed52f7a1ce22194dfa9)
**报错代码文件名：**
D:\FlutterDouBan2\FlutterDouBan2\lib\Widgets\Cached_Network_Image.dart

**Comment by sooxie** [comment]
If you're using the flutter and version  Flutter 1.12.xx
you can use modify the pubspec.yaml file
```
  flutter_cache_manager: 1.1.3
  cached_network_image: ^2.0.0
```
You can run the project.

**Comment by VelvetDream** [comment]
> If you're using the flutter and version Flutter 1.12.xx
> you can use modify the pubspec.yaml file
> 
> ```
>   flutter_cache_manager: 1.1.3
>   cached_network_image: ^2.0.0
> ```
> 
> You can run the project.

thanks ,i try is .but it still  error

```
....
flutter_cache_manager: 1.1.3

cached_network_image: ^2.0.0
...
```
still thanks

**Comment by VelvetDream** [comment]
Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'
已解决，因为版本更新的问题，API接口变动了

解决方法： 

`_imageStream.addListener(_handleImageLoaded);`

改成

`_imageStream.addListener(ImageStreamListener(_handleImageLoaded));`
