### ISSUE TITLE
大佬 状态栏字体颜色不改下吗  

### ISSUE THREAD

**Issue by BugFactory9527** [kaina404/DouBanProject#7]
学习中  期待后续

**Comment by kaina404** [comment]
haode

**Comment by kaina404** [comment]
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark); 这样就可以了

**Comment by CrazyCoderShi** [comment]
brightness也能达到相应的效果

**Comment by kaina404** [comment]
嗯嗯


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
