### ISSUE TITLE
Video播放只有声音，没有图像

### ISSUE THREAD

**Issue by sydboys** [kaina404/DouBanProject#70]
报错信息如下

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:41:31)
#1      VideoPlayerController.initialize.eventListener (package:doubanapp/widgets/video_progress_bar.dart:581:33)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:593:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
#9      _rootRun (dart:async/zone.dart:1122:38)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:41:31)
#1      VideoPlayerController.initialize.eventListener (package:doubanapp/widgets/video_progress_bar.dart:581:33)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:593:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
#9      _rootRun (dart:async/zone.dart:1122:38)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23<…>
	[C6.1.1 A042F764-DE14-407F-851F-094324B7CBB4 192.168.0.105:53082<->58.51.152.111:80/5228]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 32.300s, DNS @0.005s took 0.003s, TCP @0.009s took 0.027s
	bytes in/out: 7850718/1480, packets in/out: 5621/4, rtt: 0.014s, retransmitted packets: 0, out-of-order packets: 3218

**Comment by kaina404** [comment]
你是使用iOS还是Android的？

**Comment by kaina404** [comment]
@sydboys

**Comment by sydboys** [comment]
ios 模拟器

**Comment by sydboys** [comment]
ios 13.3

**Comment by sydboys** [comment]
还有一个问题如图：![image](https://user-images.githubusercontent.com/2426775/79960535-176ba180-84b8-11ea-9172-a8e0d69d5db2.png)

**Comment by sydboys** [comment]
![image](https://user-images.githubusercontent.com/2426775/79960677-471aa980-84b8-11ea-87b5-9d3b48b3f75a.png)

**Comment by kaina404** [comment]
@sydboys iOS模拟器好像的确不能播放，真机应该可以的。😊

**Comment by sydboys** [comment]
好！我试试真机。还有2张图的问题，麻烦看下。

**Comment by sydboys** [comment]
是不是自适应高度的问题

**Comment by sydboys** [comment]
有没有计划改造成fish-redux

**Comment by kaina404** [comment]
@sydboys 当初弄得时候，那个webview有点问题，高度有问题。关于fish redux，在计划中。后面有时间会全部使用，弄一个最新版本。

**Comment by sydboys** [comment]
那个上拉的抽屉默认位置不是最底部是什么问题？

**Comment by kaina404** [comment]
应该是没有使用SafeArea吧

**Comment by sydboys** [comment]
git 下来运行就不在底部。ios 13.3 iphone x

**Comment by kaina404** [comment]
@sydboys 你使用SafeArea包裹下试一试。

**Comment by sydboys** [comment]
好的
