### ISSUE TITLE
作者对90%怕是有很大误解啊

### ISSUE THREAD

**Issue by Saturdaycong** [kaina404/DouBanProject#72]

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年 https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠 https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元 https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

云建站，云服务器限时特惠，助力中小企业渡过疫情。个人级服务器限时特价低至102/年。 云服务器还等什么。 云建站，企业官网定制，价格便宜安全可靠。
