### ISSUE TITLE
flutter新手历时两天终于把这个项目启动起来了，贴遇到报错解决方法

### ISSUE THREAD

**Issue by cmy0816** [kaina404/DouBanProject#80]
这个项目是我运行的第一个flutter项目，完全不懂真的是遇到了各种问题。
1.  lib\util\palette_generator.dart 报错 修改如下
61行 class PaletteGenerator extends Diagnosticable 替换为 class PaletteGenerator with Diagnosticable
375行 class PaletteTarget extends Diagnosticable  替换为 class PaletteTarget with Diagnosticable
603行 class PaletteColor extends Diagnosticable 替换为 class PaletteColor with Diagnosticable
2. 需要对flutter版本进行升级 我目前的版本是1.12.13 执行升级命令 flutter upgrade 这个flutter已经安装到了全局，随便一个地方打开cmd都是可以的
3. 又出现了新的报错
FAILURE: Build failed with an exception.
    * What went wrong:
    Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
    > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-c9506cb8e93e5e8879152ff5c948b175abb5b997.
解决办法：
    这个地方修改的就是你安装flutter的地方了
    修改：flutter/packages/flutter_tools/gradle/resolve_dependencies.gradle
    flutter/packages/flutter_tools/gradle/aar_init_script.gradle
    flutter/packages/flutter_tools/gradle/flutter.gradle
    中的：https://storage.googleapis.com/download.flutter.io   替换为：http://download.flutter.io   重新编译就好了
4. 改完之后又出现了新的报错...
Could not download groovy-all.jar
解决办法
这个路径是项目中的路径
修改此文件 android\build.gradle
buildscript {
    repositories {
        // jcenter()
        // google()
        // mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google'}
        maven { url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public'}
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        // jcenter()
        // google()
        // mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google'}
        maven { url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public'}
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
直接把这些代码替换旧可以了
5. 目前为止，终于可以运行项目了，老母亲的心里深感欣慰，但遇到新的问题，闪退了。解决办法：重启
6. 开开心心的运行项目了，突然 豆芽的首页变成了 作者的简书主页了，不解，但终于不报错了..这就是最开心的事情了，可能有的错误没有记录，欢迎补充。
注：以上解决办法完全来源于网络各种试错和查找..并不是我本人解决的，我只是代码的搬运工

**Comment by wangyuuuu** [comment]
我的就只有这个类报错 运行环境是Channel stable, v1.17.3   把继承自Diagnosticable的 改成with 就能正常运行了 

再贴一下作者提供的几个工具类的依赖的更新版本

添加依赖cached_network_image: ^2.2.0+1
删除项目里面的cached_network_image_provider.dart
替换所有引用文件中的import 'package:douban_app/widgets/image/cached_network_image.dart';为import 'package:cached_network_image/cached_network_image.dart'
升级palette_generator: ^0.2.3
升级flutter_cache_manager: ^1.4.1
添加依赖shared_preferences: ^0.5.7+3


编译不过的兄弟们试一下

**Comment by shiyagn** [comment]
今天刚download的项目 直接跑起来了啊

**Comment by caoyuanyuan** [comment]
总结的不错

**Comment by kaina404** [comment]
项目已经更新到最新版本拉，可以pull并且直接运行了。卡顿可以使用Release模式运行。

**Comment by wangyuuuu** [comment]
您好，我是王宇，你的邮件我已收到，我将尽快给您回复。
