### ISSUE TITLE
Android studio启动报错

### ISSUE THREAD

**Issue by michaelPual** [kaina404/DouBanProject#81]
<img width="1071" alt="截屏2020-07-08 17 07 33" src="https://user-images.githubusercontent.com/34982385/86900224-a85c2b80-c13d-11ea-861d-d636d38d477c.png">

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年 https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠 https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元 https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

云建站，云服务器限时特惠，助力中小企业渡过疫情。个人级服务器限时特价低至102/年。 云服务器还等什么。 云建站，企业官网定制，价格便宜安全可靠。
