### ISSUE TITLE
iOS 模拟器编译不过，关于 Router, SliverOverlapAbsorber, flutter_cache_manager, cached_network_image 的错误, 我终于跑起来了

### ISSUE THREAD

**Issue by TralyFang** [kaina404/DouBanProject#84]
../../flutter/packages/flutter/lib/src/painting/image_provider.dart:578:24: Context: This is the overridden method ('load').
      ImageStreamCompleter load(T key, DecoderCallback decode);
                           ^
    lib/pages/group/group_page.dart:24:36: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:doubanapp/router.dart'.
                  Router.push(context, Router.searchPage, hintText);
                                       ^^^^^^
    lib/pages/group/group_page.dart:24:15: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:doubanapp/router.dart'.
                  Router.push(context, Router.searchPage, hintText);

这里问题怎么解决？看了代码是存在的呀，为什么编译不通过？ @kaina404 

环境
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.21.0-9.0.pre at /Users/xxx/flutter
    • Framework revision 7c6f9dd239 (9 days ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

1. 重命名Router 为 RRouter
2. 修改一下两个版本号为
cached_network_image: ^2.0.0-rc
flutter_cache_manager: 1.1.3
3. SliverOverlapAbsorber 没有匹配到child属性，将child 改成 sliver

然后就成功跑起来了，放一下截图，证明我没有骗人
![image](https://user-images.githubusercontent.com/11371532/90589287-54e6fe00-e210-11ea-8d0e-1be9ead06d3c.png)

还有一点我要提醒的，工程里面还有很多报红的地方，当时不影响编译，所以排查错误信息，请运行看控制台输出的错误信息，依次排查解决。

**Comment by NoraGithub** [comment]
SliverOverlapAbsorber 没有匹配到child属性，将child 改成 sliver

__
这个你是怎么知道的？@TralyFang

**Comment by TralyFang** [comment]
> SliverOverlapAbsorber 没有匹配到child属性，将child 改成 sliver
> 
> __
> 这个你是怎么知道的？@TralyFang

报错了啊，然后点击进去查看了属性，没有了child属性，那就是sliver咯

**Comment by xixiangnanhai** [comment]
太感谢了
