### ISSUE TITLE
如何能够顺利的编译运行？

### ISSUE THREAD

**Issue by LoveNewsweetheart** [kaina404/DouBanProject#88]
1 下载项目后，通过AndroidStudio工具导入后，打开项目中的pubspec.yaml文件，上方有一个pub get按钮，点击pub get按钮下载所需要的依赖。

2 运行Flutter run后可能会出现无法编译的问题，这时候你可能需要更改项目中的依赖的cached_network_image和flutter_cache_manager版本号，我的是改成了如下版本：
cached_network_image: ^2.0.0-rc.1
flutter_cache_manager: 1.1.3

3 将项目中的Router改一个名字，因为项目总的Router和官方的名字一样了，冲突了

4 lib\util\palette_generator.dart 报错 修改如下
61行 class PaletteGenerator extends Diagnosticable 替换为 class PaletteGenerator with Diagnosticable
375行 class PaletteTarget extends Diagnosticable 替换为 class PaletteTarget with Diagnosticable
603行 class PaletteColor extends Diagnosticable 替换为 class PaletteColor with Diagnosticable

之后，项目就会成功的跑起来了。

**Comment by echokk11** [comment]
还需要把几处`SliverOverlapAbsorber`的child改成sliver

**Comment by DreamTravelingLight** [comment]
请问你Flutter版本是多少啊，需要回退版本吗

**Comment by LoveNewsweetheart** [comment]
我的Flutter版本是 1.21.0。不需要回退版本

**Comment by IFMaggie** [comment]
解决方案里面的3 是项目里面的全部Router  都要改吗

**Comment by moyuanz** [comment]
> 解决方案里面的3 是项目里面的全部Router 都要改吗
是的，全部要改

**Comment by happy-sw** [comment]
我怎么有好多错误啊 看不懂哭唧唧

**Comment by qichangleixin** [comment]
1）Your app isn't using AndroidX

在gradle.properties中添加如下代码即可

android.enableJetifier=true
android.useAndroidX=true
2）GeneratedPluginRegistrant don't can not be applied 

如下修改
package com.example.doubanapp;

import android.os.Bundle;
**import io.flutter.embedding.android.FlutterActivity;**
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  /*@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    //GeneratedPluginRegistrant.registerWith(this);
  }*/
}

**Comment by sinduanan** [comment]
```
FAILURE: Build failed with an exception.

* Where:
Build file 'E:\demo_project\FlutterDouBan-master-new\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > org.gradle.api.file.ProjectLayout.fileProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/RegularFileProperty;
```

**Comment by sinduanan** [comment]
> ```
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'E:\demo_project\FlutterDouBan-master-new\android\build.gradle' line: 24
> 
> * What went wrong:
> A problem occurred evaluating root project 'android'.
> > A problem occurred configuring project ':app'.
>    > Failed to notify project evaluation listener.
>       > org.gradle.api.file.ProjectLayout.fileProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/RegularFileProperty;
> ```
升级下就可以了
dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
    }

**Comment by LangeZhao** [comment]
你们跑起来有数据吗，为啥我跑起来直接蹦，数据都请求不到。

**Comment by longfeihouhouhou** [comment]
> > ```
> > FAILURE: Build failed with an exception.
> > 
> > * Where:
> > Build file 'E:\demo_project\FlutterDouBan-master-new\android\build.gradle' line: 24
> > 
> > * What went wrong:
> > A problem occurred evaluating root project 'android'.
> > > A problem occurred configuring project ':app'.
> >    > Failed to notify project evaluation listener.
> >       > org.gradle.api.file.ProjectLayout.fileProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/RegularFileProperty;
> > ```
> 

build.gradle 和 gradke-wrapper.properties 中的两个版本得对应上 比如 3.5.0 =>5.6.2-all
 dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by HelloHchen** [comment]
哭唧唧，起不来

**Comment by SnailYue** [comment]
> 哭唧唧，起不来
按照楼上人的修改，还需要改这部分的 https://blog.csdn.net/csdn_aiyang/article/details/102835545，改完就可以跑起来了。

**Comment by mybirthfather** [comment]
> 1 下载项目后，通过AndroidStudio工具导入后，打开项目中的pubspec.yaml文件，上方有一个pub get按钮，点击pub get按钮下载所需要的依赖。
> 
> 2 运行Flutter run后可能会出现无法编译的问题，这时候你可能需要更改项目中的依赖的cached_network_image和flutter_cache_manager版本号，我的是改成了如下版本：
> cached_network_image: ^2.0.0-rc.1
> flutter_cache_manager: 1.1.3
> 
> 3 将项目中的Router改一个名字，因为项目总的Router和官方的名字一样了，冲突了
> 
> 4 lib\util\palette_generator.dart 报错 修改如下
> 61行 class PaletteGenerator extends Diagnosticable 替换为 class PaletteGenerator with Diagnosticable
> 375行 class PaletteTarget extends Diagnosticable 替换为 class PaletteTarget with Diagnosticable
> 603行 class PaletteColor extends Diagnosticable 替换为 class PaletteColor with Diagnosticable
> 
> 之后，项目就会成功的跑起来了。

按照这个编译之后胡报错cachemanager 找不到 ，删掉根目录下的.pages 重新点pub get 在编译就成了 ，还是得感谢这个大佬，另外没提到的一些错误都是需要迁移方法的，点击alt enter 自动修复的，总的来说 这个做的和安卓sdk版本兼容差很多

**Comment by ruanbaojun1105** [comment]
这跑出来程序太卡了，这怎么用....

**Comment by kaina404** [comment]
项目已经更新到最新版本拉，可以pull并且直接运行了。卡顿可以使用Release模式运行。

**Comment by catnuko** [comment]
> 1 下载项目后，通过AndroidStudio工具导入后，打开项目中的pubspec.yaml文件，上方有一个pub get按钮，点击pub get按钮下载所需要的依赖。
> 
> 2 运行Flutter run后可能会出现无法编译的问题，这时候你可能需要更改项目中的依赖的cached_network_image和flutter_cache_manager版本号，我的是改成了如下版本： cached_network_image: ^2.0.0-rc.1 flutter_cache_manager: 1.1.3
> 
> 3 将项目中的Router改一个名字，因为项目总的Router和官方的名字一样了，冲突了
> 
> 4 lib\util\palette_generator.dart 报错 修改如下 61行 class PaletteGenerator extends Diagnosticable 替换为 class PaletteGenerator with Diagnosticable 375行 class PaletteTarget extends Diagnosticable 替换为 class PaletteTarget with Diagnosticable 603行 class PaletteColor extends Diagnosticable 替换为 class PaletteColor with Diagnosticable
> 
> 之后，项目就会成功的跑起来了。

第4个可以通过添加环境变量FLUTTER_STORAGE_BASE_URL来解决
