### ISSUE TITLE
IOS 模拟器播放视频有问题。

### ISSUE THREAD

**Issue by seraphzxz87** [kaina404/DouBanProject#89]
IOS 模拟器无法播放视频，有声音没有图像。

**Comment by Andrew5** [comment]
你是怎么跑起来的 ，用什么编译器啊，我的现在跑不起来，用a android Studio和Visual Studio Code都跑不起来

**Comment by kaina404** [comment]
iOS模拟器原生就不支持播放，这是系统的问题。
