### ISSUE TITLE
【建议】建议作者更新下文档

### ISSUE THREAD

**Issue by QJJMSK** [kaina404/DouBanProject#95]
工程的文档太旧了，而且还有问题，flutter的sdk版本太旧了，导致有些类或是类名都找不到，我这边更新到v1.15.7，同时还报了一个Android Flutter AndroidX incompatibilities，请查看这个地址   https://blog.csdn.net/perfectnihil/article/details/103557112，做了上面两个操作后，就编译通过了。

**Comment by kaina404** [comment]
项目已经更新到最新版本拉，可以pull并且直接运行了。
