### ISSUE TITLE
项目还更新么？好卡呀 

### ISSUE THREAD

**Issue by mybirthfather** [kaina404/DouBanProject#96]
类似 TAB 界面 statewidget 都应该 with AutomaticKeepAliveClientMixin  实现类似fragment 懒加载 不是每次都重建 界面否则tab切换是真的卡到爆 希望优化一下

**Comment by kaina404** [comment]
项目已经更新到最新版本拉，可以pull并且直接运行了。卡顿可以试一试Release模式运行。
