### ISSUE TITLE
项目跑不起来，报错信息如下

### ISSUE THREAD

**Issue by Andrew5** [kaina404/DouBanProject#99]
[FlutterDouBan] flutter pub get
Running "flutter pub get" in FlutterDouBan...                      37.0s
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
exit code 0

**Comment by kaina404** [comment]
项目已经更新到最新版本拉，可以pull并且直接运行了。

**Comment by 330132662** [comment]
本邮箱不作为工作生活用 请联系 ***@***.***

**Comment by shijianmei** [comment]
This app is using a deprecated version of the Android embedding.

**Comment by huangchengzuo** [comment]
你好！
邮件已收到！谢谢！
